#!/bin/sh

# install build tools
apk --update add gcc linux-headers musl-dev make

# copy source, so patches won't change the originals
mkdir /build
cp -pR /source/* /build
cd /build

patch_files="
	busybox-1.11.1-bb.patch
	bb-app-location.patch
	loginutils-sha512.patch
	udhcpc-discover-retries.patch

	busybox-1.24.2-CVE-2016-2147.patch
	busybox-1.24.2-CVE-2016-2148.patch

	0001-ifupdown-pass-interface-device-name-for-ipv6-route-c.patch
	0001-ifupdown-use-x-hostname-NAME-with-udhcpc.patch

	0001-diff-add-support-for-no-dereference.patch

	1000-fbsplash-use-virtual-y-size-in-mmap-size-calculation.patch
	1001-fbsplash-support-console-switching.patch
	1002-fbsplash-support-image-and-bar-alignment-and-positio.patch

	2001-modutils-merge-module_entry-and-module_info-to-commo.patch
	2002-depmod-support-generating-kmod-binary-index-files.patch
	2003-modinfo-fix-argument-parsing-and-printing-of-firmwar.patch

	3001-login-move-check_securetty-to-libbb.patch
	3002-libbb-allow_blank-argument-for-ask_and_check_passwor.patch
	3003-su-FEATURE_SU_NULLOK_SECURE.patch

	0001-ash-backport-fix-for-here-document-issues.patch
	0001-ash-fix-error-during-recursive-processing-of-here-do.patch

	glibc.patch"

# modify source files
for i in $patch_files; do
	patch -p1 -i gns3_build/$i || exit 1
done
cp -p gns3_build/nologin.c loginutils/

# compile
cp -p gns3_build/busyboxconfig .config
make silentoldconfig || exit 1
make || exit 1
mv busybox /source
